Book_My_Movie_show/MovieCoreMVC_UI/Controllers/BookShowController.cs
using Book_Show_Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVC_UI.Controllers
{
    public class BookShowController : Controller
    {
        private IConfiguration _configuration;
        public BookShowController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<BookShow> users = null;

            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/GetALLBookShow";
                using (var resonse = await client.GetAsync(endpoint))
                {
                    if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await resonse.Content.ReadAsStringAsync();
                        users = JsonConvert.DeserializeObject<IEnumerable<BookShow>>(result);
                    }
                }
            }
            return View(users);
        }

        //adding booking
        public async Task<IActionResult> BookShowEntry()
        {

            /*IEnumerable<ShowTiming> showone = null;

            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/GetShowTiming";
                using (var resonse = await client.GetAsync(endpoint))
                {
                    if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await resonse.Content.ReadAsStringAsync();
                        showone = JsonConvert.DeserializeObject<IEnumerable<ShowTiming>>(result);
                    }
                }
            }*/
            BookShow bookshow = new BookShow();
            int ShowTimingIds = Convert.ToInt32(TempData["ShowTimingFinalId"]);
            ShowTiming showTiming = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/GetShowTimingById?MovieId=" + ShowTimingIds;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showTiming = JsonConvert.DeserializeObject<ShowTiming>(result);
                    }

                }
            }
            bookshow.ShowTimingId = showTiming.ShowTimingId;
            bookshow.TicketCost=showTiming.ShowCost;
            
            TempData.Keep();

            /*foreach (var show in showone)
            {
                bookshow.ShowTimingId = show.ShowTimingId;
            }*/
            int a =Convert.ToInt32( TempData["UserMantainceid"]);

            /*dynamic a = TempData["UserMantainceid"];*/
            bookshow.UserId=Convert.ToInt32(a);
            return View(bookshow);
        }
        [HttpPost]
        public async Task<IActionResult> BookShowEntry(BookShow bookShow)
        {
            bookShow.TicketCost = bookShow.NoOfTickets * bookShow.TicketCost;
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                
                StringContent content = new StringContent(JsonConvert.SerializeObject(bookShow), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"]+ "BookShow/AddBookShow";
                using (var response = await client.PostAsync(endpoint,content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Your Booking succesful";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }

            return View();
        }



        //Edit BookShow
        public async Task<IActionResult> EditBookShow(int BookShowId)
        {
            BookShow BookShow = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/GetBookShowById?MovieId=" + BookShowId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        BookShow = JsonConvert.DeserializeObject<BookShow>(result);
                    }

                }
            }
            return View(BookShow);
        }

        [HttpPost]
        public async Task<IActionResult> EditBookShow(BookShow BookShow)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(BookShow), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/UpdateBookShow";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        //delete movie
        public async Task<IActionResult> DeleteBookShow(int BookShowId)
        {
            BookShow movie = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/GetBookShowById?MovieId=" + BookShowId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<BookShow>(result);
                    }

                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBookShow(BookShow BookShow)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/DeleteBookShow?BookId=" + BookShow.BookShowId;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "BookShow delete succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetShowUserId()
        {
            int userProfileId = Convert.ToInt32(TempData["UserMantainceid"]);
            IEnumerable<BookShow> bookShow = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "BookShow/GetBookShowUserId?userId=" + userProfileId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        bookShow = JsonConvert.DeserializeObject<IEnumerable<BookShow>>(result);
                    }

                }
            }
            return View(bookShow);
        }
    }
}

Book_My_Movie_show/MovieCoreMVC_UI/Controllers/LocationController.cs
using Book_Show_Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVC_UI.Controllers
{
    public class LocationController : Controller
    {
        private IConfiguration _configuration;
        
        public LocationController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Location> users = null;

            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Location/GetLocation";
                using (var resonse = await client.GetAsync(endpoint))
                {
                    if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await resonse.Content.ReadAsStringAsync();
                        users = JsonConvert.DeserializeObject<IEnumerable<Location>>(result);
                    }
                }
            }
            return View(users);
        }
        public IActionResult LocationEntry()
        {
            return View();    
        }
        [HttpPost]
        public async Task<IActionResult> LocationEntry(Location location)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(location), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Location/AddLocation";
                using (var response = await client.PostAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Location details saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        //Edit Location
        public async Task<IActionResult> EditLocation(int LocationId)
        {
            Location location = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Location/GetLocationById?MovieId=" + LocationId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        location = JsonConvert.DeserializeObject<Location>(result);
                    }

                }
            }
            return View(location);
        }

        [HttpPost]
        public async Task<IActionResult> EditLocation(Location location)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(location), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Location/UpdateLocation";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        //delete movie
        public async Task<IActionResult> DeleteLocation(int LocationId)
        {
            Location movie = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Location/GetLocationById?MovieId=" + LocationId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Location>(result);
                    }

                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteLocation(Location location)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Location/DeleteLocation?LocationId=" + location.LocationId;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Location delete succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }
    }
}

Book_My_Movie_show/MovieCoreMVC_UI/Views/BookShow/BookShowEntry.cshtml
@{
    Layout = "~/Views/Shared/UserPage.cshtml";
}
@model Book_Show_Entity.BookShow
@*<div>
    <a asp-controller="BookShow" asp-action="Index">BookShow Details</a>
</div>*@



<form method="post" enctype="multipart/form-data">
    <h2>BookShow Entry</h2><hr />
    <div class="form-group">
        <label>ShowTimingId</label>
        <input type="number" asp-for="ShowTimingId" class="form-control" placeholder="enter a ShowTimingId" required />
    </div>
   
    <div class="form-group">
        <label>UserId</label>


        <input type="number" asp-for="UserId" class="form-control" placeholder="enter a UserId" required />
    </div>
    <div class="form-group">
        <label>Price For 1 ticket</label>
        <input type="number" asp-for="TicketCost" class="form-control" placeholder="Ticket Cost" required />
    </div>
    <div class="form-group">
        <label>No Of Tickets You Want?</label>
        <input type="number" asp-for="NoOfTickets" class="form-control" placeholder="enter a NoOfTickets" required />
    </div>
    


    <hr />
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>
@*@string a=TempData["dabbaemail"].ToString();*@

Book_My_Movie_show/MovieCoreMVC_UI/Views/BookShow/DeleteBookShow.cshtml
@model Book_Show_Entity.BookShow
@{
    ViewData["Title"] = "DeleteBookShow";
}

<h1>DeleteBookShow</h1>

<form method="post" enctype="multipart/form-data">
    <h2>Delete Movie</h2><hr />
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="BookShowId" class="form-control" placeholder="enter a movie name" required />
    </div>
    <hr />
    <input type="submit" value="Delete" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>

Book_My_Movie_show/MovieCoreMVC_UI/Views/BookShow/EditBookShow.cshtml
@model Book_Show_Entity.BookShow
@{
    ViewData["Title"] = "EditBookShow";
}

<h1>EditBookShow</h1>

<form method="post" enctype="multipart/form-data">
    <h2>BookShow Entry</h2><hr />
    <div class="form-group">
        <label>ShowTimingId</label>
        <input type="number" asp-for="ShowTimingId" class="form-control" placeholder="enter a ShowTimingId" required />
    </div>
    <div class="form-group">
        <label>UserId</label>
        <input type="number" asp-for="UserId" class="form-control" placeholder="enter a UserId" required />
    </div>
    <div class="form-group">
        <label>NoOfTickets</label>
        <input type="number" asp-for="NoOfTickets" class="form-control" placeholder="enter a NoOfTickets" required />
    </div>
    <div class="form-group">
        <label>TicketCost</label>
        <input type="number" inputmode="decimal" asp-for="TicketCost" class="form-control" placeholder="enter a TicketCost" required />
    </div>


    <hr />
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>

Book_My_Movie_show/MovieCoreMVC_UI/Views/BookShow/GetShowUserId.cshtml
@{
    Layout = "~/Views/Shared/UserPage.cshtml";
}
@model IEnumerable< Book_Show_Entity.BookShow>

@*<div>
    <a asp-controller="Location" asp-action="LocationEntry">ADD Movie Location</a>
</div>*@


@foreach (var movie in Model)
{//default put as model it is keyword in MVC
                 //@ we used to refer the csharp code
                 //razer view compiler.it will convert the code to html understand file
    <section class="vh-10" style="background-color: #eee;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-md-9 col-lg-7 col-xl-5">
                    <div class="card" style="border-radius: 20px; background-color: #93e2bb;">
                        <div class="card-body p-4 text-black">
                            <div>
                                <h4 class="mb-4">Your Ticket : Confirmed</h4>
                                <div class="d-flex align-items-center justify-content-between mb-3">
                                    <p class="small mb-0"><i class="far fa-clock me-2"></i>Total Hours: 3 hours</p>
                                    <p class="fw-bold mb-0">@movie.ShowTiming.ShowCost</p>
                                    <p class="fw-bold mb-0">@movie.NoOfTickets</p>
                                    <p class="fw-bold mb-0">@movie.TicketCost</p>
                                </div>
                            </div>
                            @*<div class="d-flex align-items-center mb-4">
                                <div class="flex-shrink-0">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-2.webp"
                                     alt="Generic placeholder image" class="img-fluid rounded-circle border border-dark border-3"
                                     style="width: 70px;">
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <div class="d-flex flex-row align-items-center mb-2">
                                        <p class="mb-0 me-2">sheisme</p>
                                        <ul class="mb-0 list-unstyled d-flex flex-row" style="color: #1B7B2C;">
                                            <li>
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                            <li>
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                            <li>
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                            <li>
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                            <li>
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                        </ul>
                                    </div>
                                    <div>
                                        <button type="button" class="btn btn-outline-dark btn-rounded btn-sm"
                                            data-mdb-ripple-color="dark">
                                            + Follow
                                        </button>
                                        <button type="button" class="btn btn-outline-dark btn-rounded btn-sm"
                                            data-mdb-ripple-color="dark">
                                            See profile
                                        </button>
                                        <button type="button" class="btn btn-outline-dark btn-floating btn-sm"
                                            data-mdb-ripple-color="dark">
                                            <i class="fas fa-comment"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <hr>*@
                            <div class="d-flex align-items-center mb-4">
                                <div class="flex-shrink-0">
                                    <img src="data:image/JPG;base64,@Convert.ToBase64String(@movie.ShowTiming.Movie.ImgPoster)"
                                     alt="Generic placeholder image" class="img-fluid rectangle border border-dark border-3"
                                     style="width: 100px;">
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <div class="d-flex flex-row align-items-center mb-2">
                                        <div><h2 style="padding-left:50px;"> @movie.ShowTiming.Movie.MovieName</h2></div>

                                        <div><h5 style="padding-left:50px;">@movie.ShowTiming.Movie.MovieType</h5></div>
                                        <h5 style="padding-left:50px;"></h5>
                                        <h5 style="padding-left:50px;"></h5>
                                        <ul class="mb-0 list-unstyled d-flex flex-row" style="color:gold;">
                                            <li>
                                               
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                            <li>
                                                
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                            <li>
                                                
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                            <li>
                                               
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                            <li>
                                                <i class="fas fa-star fa-xs"></i>
                                            </li>
                                        </ul>
                                    </div>
                                    <div>
                                       
                                    </div>
                                </div>
                                <div><h5 style="padding-left:50px;">@movie.ShowTiming.Movie.MovieLanguage</h5></div>
                                <div><h5 style="padding-left:50px;"> @movie.ShowTiming.Movie.MovieDesc</h5></div>
                            </div>
                            <hr>
                            <p class="my-4 pb-1">Adress:</p>
                            <button type="button" class="btn btn-success btn-rounded btn-block btn-lg">
                                <i class="far fa-clock me-2"></i>Pay Now
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

                }

Book_My_Movie_show/MovieCoreMVC_UI/Views/BookShow/Index.cshtml
@model IEnumerable<Book_Show_Entity.BookShow>
@{
    ViewData["Title"] = "Index";
}

@*<div>
    <a asp-controller="BookShow" asp-action="BookShowEntry">BookShow Entry</a>
</div>*@

<div class="row">
    <div class="col-12">
        <center><h3>Book Show Details</h3></center>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>BookShowId</th>
                    <th>User Name</th>
                    <th>Movie Name</th>
                    <th>Theater Name</th>
                    <th>Location</th>
                    <th>Show cost</th>
                    <th>NoOfTickets</th>
                    
                    <th>TicketCost</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var movie in Model)
                {//default put as model it is keyword in MVC
                 //@ we used to refer the csharp code
                 //razer view compiler.it will convert the code to html understand file
                    <tr>
                        <td>@movie.BookShowId</td>
                        <td>@movie.UserDetails.UserName</td>
                        <td>@movie.ShowTiming.Movie.MovieName</td>
                        <td>@movie.ShowTiming.Theater.Name</td>
                        <td>@movie.ShowTiming.Theater.Location.LocationDesc</td>
                        <td>@movie.ShowTiming.ShowCost</td>
                        <td>@movie.NoOfTickets</td>
                        
                        <td>@movie.TicketCost</td>
                        <td><a asp-controller="BookShow" asp-action="EditBookShow" asp-route-BookShowId="@movie.BookShowId">Edit</a></td>
                        <td><a asp-controller="BookShow" asp-action="DeleteBookShow" asp-route-BookShowId="@movie.BookShowId">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>