Book_My_Movie_show/MovieCoreMVC_UI/Controllers/MovieController.cs
using Book_Show_Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMVC_UI.Controllers
{
    public class MovieController : Controller
    {
        private IConfiguration _configuration;
        public MovieController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Movie> movieresult = null;
            using (HttpClient client = new HttpClient())
            {
                
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovies";
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result=await response.Content.ReadAsStringAsync();
                        movieresult=JsonConvert.DeserializeObject<IEnumerable<Movie>>(result);
                    }
                  
                }
            }
            return View(movieresult);
        }
        public IActionResult MovieEntry()
        {
            List<SelectListItem> language = new List<SelectListItem>()
            {
                new SelectListItem{Value="Select",Text="select"},
                new SelectListItem{Value="Tamil",Text="Tamil"},
                new SelectListItem{Value="English",Text="English"},
                new SelectListItem{Value="Kannada",Text="Kannada"},
            };
                ViewBag.languagelist = language;
            return View();
        
            
        }
        [HttpPost]
        public async Task<IActionResult> MovieEntry(Movie movie)
        {
            ViewBag.status = "";

            if (Request.Form.Files.Count > 0)
            {
                MemoryStream ms = new MemoryStream();
                Request.Form.Files[0].CopyTo(ms);
                movie.ImgPoster = ms.ToArray();
            }
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/AddMovie";
                using (var response = await client.PostAsync(endpoint, content)) 
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else{
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }


        //Edit Movie
        public async Task<IActionResult> EditMovie(int movieId)
        {
            Movie movie = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovieById?MovieId=" + movieId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(result);
                    }

                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> EditMovie(Movie movie)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(movie), Encoding.UTF8, "application/json");
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/UpdateMovie";
                using (var response = await client.PutAsync(endpoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie details saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }

        //delete movie
        public async Task<IActionResult> DeleteMovie(int movieId)
        {
            Movie movie = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovieById?MovieId=" + movieId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(result);
                    }

                }
            }
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMovie(Movie movie)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                
                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/DeleteMovie?movieId="+movie.MovieId;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Movie delete saved succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }



        /*        public IActionResult EditMovie()
                {
                    return View();
                }*/


    }
}

Book_My_Movie_show/MovieCoreMVC_UI/Controllers/UserViewController.cs
using Book_Show_Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Location = Book_Show_Entity.Location;

namespace MovieCoreMVC_UI.Controllers
{
    public class UserViewController : Controller
    {
        private IConfiguration _configuration;
        public UserViewController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Movie> movieresult = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovies";
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK) 
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieresult = JsonConvert.DeserializeObject<IEnumerable<Movie>>(result);
                    }

                }
            }
            return View(movieresult);
        }



        //Show timings user
        public async Task<IActionResult> ShowTimingEntryUser(int MovieId)
        {
            ShowTiming show=new ShowTiming();
            

            //Movie Name Priniting
            Movie movie = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Movie/GetMovieById?MovieId=" + MovieId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movie = JsonConvert.DeserializeObject<Movie>(result);
                    }

                }
            }
            show.MovieId = movie.MovieId;
            
            List<Location> locations = new List<Location>();
            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "Location/GetLocation";
                using (var resonse = await client.GetAsync(endpoint))
                {
                    if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await resonse.Content.ReadAsStringAsync();
                        locations = JsonConvert.DeserializeObject<List<Location>>(result);
                    }
                }
            }
            List<SelectListItem> language = new List<SelectListItem>();
            language.Add(new SelectListItem { Value = "select", Text = "select" });
            foreach (var item in locations)
            {
                language.Add(new SelectListItem { Value = item.LocationId.ToString(), Text = item.LocationDesc });
            }

            ViewBag.Locationlist = language;

            return View(show);
        }


        
        public IActionResult SelectTheater(ShowTiming show,int LocationId)
        {
            show.Theater.Location.LocationId = LocationId;
            return View(show);
        }



        //for selecting theater

        [HttpPost]

        public async Task<IActionResult> SelectTheater(ShowTiming show)
        {
            /*show.Theater.Location.LocationId= LocationId;*/
            IEnumerable<Theater> movieresult = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Theater/GetTheater";
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        movieresult = JsonConvert.DeserializeObject<IEnumerable<Theater>>(result);
                    }

                }
            }

            List<SelectListItem> theater = new List<SelectListItem>();


            theater.Add(new SelectListItem { Value = "select", Text = "select" });
            foreach (var item in movieresult)
            {
                if (item.LocationId == show.Theater.LocationId)
                {
                    theater.Add(new SelectListItem { Value = item.TheatreId.ToString(), Text = item.Name });
                }
            }
            ViewBag.Theaterlist = theater;

            //list of showtiming
            List<ShowTiming> showtimings = null;

            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/GetShowTiming";
                using (var resonse = await client.GetAsync(endpoint))
                {
                    if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await resonse.Content.ReadAsStringAsync();
                        showtimings = JsonConvert.DeserializeObject<List<ShowTiming>>(result);
                    }
                }
            }

            List<SelectListItem> Showtimings = new List<SelectListItem>();


            Showtimings.Add(new SelectListItem { Value = "select", Text = "select" });
            foreach (var item in showtimings)
            {
                if (item.MovieId == show.MovieId && item.Theater.LocationId==show.Theater.LocationId)
                {
                    Showtimings.Add(new SelectListItem { Value = item.ShowTime.ToString(), Text = item.ShowTime.ToString() });
                }
            }

            ViewBag.ShowTimeList = Showtimings;
            return View(show);
        }

        //Creating show timings 


        [HttpPost]
        public async Task<IActionResult> ShowTimingEntryUser(ShowTiming show)
        {
            List<ShowTiming> showtimings = null;

            using (HttpClient client = new HttpClient())
            {
                string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/GetShowTiming";
                using (var resonse = await client.GetAsync(endpoint))
                {
                    if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await resonse.Content.ReadAsStringAsync();
                        showtimings = JsonConvert.DeserializeObject<List<ShowTiming>>(result);
                    }
                }
            }
            foreach(var item in showtimings)
            {
                if(item.MovieId==show.MovieId && item.TheatreId==show.TheatreId && item.Theater.LocationId==show.Theater.LocationId && item.ShowTime == show.ShowTime)
                {
                    TempData["ShowTimingFinalId"]= item.ShowTimingId;
                    return RedirectToAction("BookShowEntry", "BookShow");
                    
                    
                }
               
            }


            return View();
        }


        //UserProfile

        public async Task<IActionResult> UserProfile()
        {
            int userProfileId = Convert.ToInt32(TempData["UserMantainceid"]);
            TempData.Keep();
            UserDetails userDetails = null;
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "User/GetUserById?movieId=" + userProfileId;
                using (var response = await client.GetAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        userDetails = JsonConvert.DeserializeObject<UserDetails>(result);
                    }

                }
            }
            return View(userDetails);
           
        }

        //my bookings
        
        public async Task<IActionResult> MyBookings()
        {
            return View();
        }

            //pick the last data
            /*  public async Task<IActionResult> GetLastShow()
              {
                  ShowTiming showone = null;

                  using (HttpClient client = new HttpClient())
                  {
                      string endpoint = _configuration["WebApiBaseUrl"] + "ShowTiming/GetShowTiming";
                      using (var resonse = await client.GetAsync(endpoint))
                      {
                          if (resonse.StatusCode == System.Net.HttpStatusCode.OK)
                          {
                              var result = await resonse.Content.ReadAsStringAsync();
                              showone = JsonConvert.DeserializeObject<ShowTiming>(result);
                          }
                      }
                  }
                  return View(showone);
              }*/

        }
    }

Book_My_Movie_show/MovieCoreMVC_UI/Views/UserView/Index.cshtml
@{
    Layout = "~/Views/Shared/UserPage.cshtml";
    }

<center>
    <div style="background-color:lightblue; ">
        <h1 class="display-4">Book<span style="color:red">MY</span>Show</h1>
        <form id="form">
            <input type="search" id="query" name="q" placeholder="Search..." style="width:500px">
            <button>Search</button>
        </form>
    </div>
</center>

<hr />
@model IEnumerable<Book_Show_Entity.Movie>
@{
    ViewData["Title"] = "Index";
}



@*<div class="row">
    <div class="col-md-4" style="height:100px;">
    <div class=" alert alert-success">Movie</div>
    </div>
    <div class="col-md-4"style="height:100px;background-color:aqua">
        <div class="card">
            <div class="card" style="width: 18rem;">
                <img src="~/download.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
         </div>
    </div>
    <div class="col-md-4"style="height:100px;background-color:red">Movie2</div>


</div>*@

@*<div>
    <hr />
    <a asp-controller="Movie" asp-action="MovieEntry">MovieEntry</a>
    <hr />

</div>*@

<div class="row">
    @foreach (var item in Model)
    {
        @* <div class="card col-1">
    </div>*@
        <div class="card col-3">
            <img src="data:image/JPG;base64,@Convert.ToBase64String(item.ImgPoster)" style="height:350px" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">@item.MovieName</h5>
                <h5 class="card-title">@item.MovieLanguage</h5>

                <p class="card-text">@item.MovieDesc.</p>
                @*<a class="btn-outline-danger btn-block" asp-controller="BookShow" asp-action="BookShowEntry" asp-route-MovieId="@item.MovieId "><span style="color:white">Book Show</span></a>*@
                <a asp-controller="UserView" asp-action="ShowTimingEntryUser" class="btn btn-danger" asp-route-MovieId="@item.MovieId">Book Show</a>
            </div>
        </div>

    }
</div>

Book_My_Movie_show/MovieCoreMVC_UI/Views/UserView/MyBookings.cshtml
@{
    Layout = "~/Views/Shared/UserPage.cshtml";
}

<section class="vh-100" style="background-color: #5f59f7;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card mb-5" style="border-radius: 15px;">
                    <div class="card-body p-4">
                        <h3 class="mb-3">Program Title</h3>
                        <p class="small mb-0">
                            <i class="far fa-star fa-lg"></i> <span class="mx-2">|</span> Created by
                            <strong>MDBootstrap</strong> on 11 April , 2021
                        </p>
                        <hr class="my-4">
                        <div class="d-flex justify-content-start align-items-center">
                            <p class="mb-0 text-uppercase">
                                <i class="fas fa-cog me-2"></i> <span class="text-muted small">settings</span>
                            </p>
                            <p class="mb-0 text-uppercase">
                                <i class="fas fa-link ms-4 me-2"></i> <span class="text-muted small">program link</span>
                            </p>
                            <p class="mb-0 text-uppercase">
                                <i class="fas fa-ellipsis-h ms-4 me-2"></i> <span class="text-muted small">program link</span>
                                <span class="ms-3 me-4">|</span>
                            </p>
                            <a href="#!">
                                <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-2.webp" alt="avatar"
                                     class="img-fluid rounded-circle me-3" width="35">
                            </a>
                            <button type="button" class="btn btn-outline-dark btn-sm btn-floating">
                                <i class="fas fa-plus"></i>
                            </button>
                        </div>
                    </div>
                </div>
              
            </div>
        </div>
    </div>
</section>

Book_My_Movie_show/MovieCoreMVC_UI/Views/UserView/SelectTheater.cshtml
@{
    Layout = "~/Views/Shared/UserPage.cshtml";
}
@model Book_Show_Entity.ShowTiming
@*<div>
    <hr />
    <a asp-controller="ShowTiming" asp-action="Index">Show Timing</a>
    <hr />

</div>*@
<form method="post" enctype="multipart/form-data">
    <h2>Show Timing Entry</h2><hr />
    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control" placeholder="enter a movie id" required />
    </div>

    @*  <div class="form-group">
    <label>Theater Id</label>
    <input type="text" asp-for="TheatreId" class="form-control" placeholder="enter a Theatre Id" required />
    </div>*@
    <div class="form-group">
        <label>select Location</label>
        <input type="text" asp-for="Theater.LocationId" class="form-control" placeholder="enter a movie id" required />
    </div>
    <div class="form-group">
        <label>select Location</label>
        <select asp-for="TheatreId" asp-items="@ViewBag.Theaterlist"></select>
    </div>

    <div class="form-group">
        <label>select Timings</label>
        <select asp-for="ShowTime" asp-items="@ViewBag.ShowTimeList"></select>
    </div>
    <hr />
    @* <a asp-controller="BookShow" class="btn btn-outline-secondary"  asp-action="BookShowEntry" asp-route-ShowTimingId="ShowTimingId">Submit</a>*@
    @*<a asp-controller="BookShow" asp-action="BookShowEntry" class="btn btn-danger" asp-route-ShowTimingId="ShowTimingId">Book Show</a>*@
    <input type="submit" value="Save" asp-controller="UserView" asp-action="ShowTimingEntryUser" asp-route-ShowTimingId="ShowTimingId" class="btn btn-outline-success" />
    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <a asp-controller="BookShow" class="btn btn-outline-secondary" asp-action="BookShowEntry" asp-route-bookshow="ShowTimingId">Next Page</a>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>

Book_My_Movie_show/MovieCoreMVC_UI/Views/UserView/ShowTimingEntryUser.cshtml
@*@{
    ViewData["Title"] = "ShowTimingEntryUser";
}*@

@model Book_Show_Entity.ShowTiming

@{
    Layout = "~/Views/Shared/UserPage.cshtml";
}

@*<div>
    <hr />
    <a asp-controller="ShowTiming" asp-action="Index">Show Timing</a>
    <hr />

</div>*@
<form method="post" enctype="multipart/form-data">
    <h2>Show Timing Entry</h2><hr />


    <div class="form-group">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control" placeholder="enter a movie id" required />
    </div>

    @*  <div class="form-group">
    <label>Theater Id</label>
    <input type="text" asp-for="TheatreId" class="form-control" placeholder="enter a Theatre Id" required />
    </div>*@
    <div class="form-group">
        <select class="selectpicker" data-style="btn-danger" asp-for="Theater.LocationId" asp-items="@ViewBag.Locationlist">
           
        </select>
       
    </div>

   @* <div class="form-group">
        <label>Show Time</label>
        <input type="datetime-local" asp-for="ShowTime" class="form-control" placeholder="enter a Show Time" required />
    </div>*@
    <hr />
    @* <a asp-controller="BookShow" class="btn btn-outline-secondary"  asp-action="BookShowEntry" asp-route-ShowTimingId="ShowTimingId">Submit</a>*@
    @*<a asp-controller="BookShow" asp-action="BookShowEntry" class="btn btn-danger" asp-route-ShowTimingId="ShowTimingId">Book Show</a>*@
    <input type="submit" value="Search" asp-controller="UserView" asp-action="SelectTheater" asp-route-LocationId="LocationId" class="btn btn-outline-success" />
@*    <input type="reset" value="Reset" class="btn btn-outline-secondary" />
    <a asp-controller="BookShow" class="btn btn-outline-secondary" asp-action="BookShowEntry" asp-route-bookshow="ShowTimingId">Next Page</a>*@
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">@ViewBag.message</div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">@ViewBag.message</div>
    }
</form>

Book_My_Movie_show/MovieCoreMVC_UI/Views/UserView/UserProfile.cshtml
@{
    Layout = "~/Views/Shared/UserPage.cshtml";
}
@model Book_Show_Entity.UserDetails;
<html>
    <head>
    <script type="text/javascript">
        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>

    </head>
    <body>

    <section class="vh-100" style="background-color: #f4f5f7;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-lg-6 mb-4 mb-lg-0">
                    <div class="card mb-3" style="border-radius: .5rem;">
                        <div class="row g-0">
                            <div class="col-md-4 gradient-custom text-center text-white"
                                 style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
                                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                                     alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
                                <h5>Marie Horwitz</h5>
                                <p>Web Designer</p>
                                <i class="far fa-edit mb-5"></i>
                            </div>
                            <div class="col-md-8">
                                <div class="card-body p-4">
                                    <h6>Information</h6>
                                    <hr class="mt-0 mb-4">
                                    <div class="row pt-1">
                                        <div class="col-6 mb-3">
                                            <h6>Email</h6>
                                            <p class="text-mu-ted">@Model.UserEmail</p>
                                        </div>
                                        <div class="col-6 mb-3">
                                            <h6>Phone</h6>
                                            <p class="text-muted">@Model.UserPhoneNo</p>
                                        </div>
                                    </div>
                                    <h6>Personal Information</h6>
                                    <hr class="mt-0 mb-4">
                                    <div class="row pt-1">
                                        <div class="col-6 mb-3">
                                            <h6>Name</h6>
                                            <p class="text-muted">@Model.UserName</p>
                                        </div>
                                        <div class="col-6 mb-3">
                                            <h6>User ID</h6>
                                            <p class="text-muted">@Model.UserId</p>
                                        </div>
                                    </div>
                                    <div>
                                        <a class="btn btn-outline-primary" type="button" value="Logout" asp-controller="UserDetails" asp-action="UserLogin">Logout</a>
                                    </div>
                                    <div class="d-flex justify-content-start">
                                        <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                                        <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                                        <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </body>
</html>